config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories
  resources :favorites
  resources :projects
  resources :promises
  devise_for :users, :path_prefix => 'd', controllers: { :omniauth_callbacks => 'callbacks' }
  resources :finances do
    member do
      get :confirm_finance
    end
  end
  resources :users, only: [:show]
  get 'new_promise', to: 'promises#new'
  get 'my_projects', to: 'projects#show_my'
  get 'show_all', to: 'users#show_all'
  get 'show_my_fav', to: 'favorites#show_my_fav'
  get 'show_my_waiting', to: 'projects#show_my_waiting'
  get 'show_my_funded', to: 'projects#show_my_funded'
  get 'show_outstanding', to: 'projects#show_outstanding'
  get 'make_outstanding', to: 'projects#make_outstanding'
  get 'download_image_p', to: 'projects#download_file'
  get 'download_image_u', to: 'users#download_file'
  get 'contribution/create', to: 'contributions#create'
  get 'finance/create', to: 'finances#create'
  get 'new_facebook', to: 'users#new_facebook'
  resources :contributions do
    member do
      get :confirm_contribution
    end
  end

  resources :projects do
    put :favorite, on: :member
  end
  get 'show_by_cat', to: 'categories#show_by_cat'
  get 'show_user_projects', to: 'projects#show_user_projects'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
  resources :users, :controller => "users"
  resources :promises, :controller => "promises"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [ :facebook ]
  has_attached_file :avatar, styles: { medium: "300x300>", small: "80x80#", thumb: "30x30#" }, default_url: "generic_profile.jpeg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :first_name, presence: true, length: { minimum: 2}
  validates :last_name, presence:true, length: {minimum: 2}
  has_many :projects, :dependent => :destroy
  has_many :favorites, :dependent => :destroy
  has_many :favorite_projects, through: :favorites, source: :project
  has_many :contributions, :dependent => :destroy
  has_many :projects_founded, through: :contributions, source: :project
  has_many :finance, :dependent => :destroy
  has_many :promises_bought, through: :finance, source: :promise

  def is_admin?
    self.admin
  end

  def self.from_omniauth (auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.password = Devise.friendly_token[0, 20]
    end
  end

  def print
    puts self.uid
    puts self.provider
    puts self.first_name
    puts self.last_name
    puts self.email
    puts self.phone
    puts self.address
    puts self.country
    puts self.city
    puts self.password
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :isadmin?, :only[:index, :create, :edit, :show, :update]
  def show
    @user = User.find(params[:id])
    @projects = @user.projects.count
    @founded = @user.contributions.where(status: true).count
    @founded += @user.finance.where(status: true).count
    @waiting = @user.contributions.where(status: false).count
    @waiting += @user.finance.where(status: false).count
  end

  def show_all
    @users = User.all
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def new_facebook
    aux = User.find_by_email(params[:info][:email])
    if aux
      sign_in_and_redirect aux, success: 'Successfully signed up through Facebook'
    end
    @user = User.new
    @user.uid = params[:uid]
    @user.provider = params[:provider]
    info = params[:info]
    @user.email = info[:email]
    @user.first_name = info[:first_name]
    @user.last_name = info[:last_name]
    @user.password = Devise.friendly_token[0, 20]
  end

  def create
    @user = User.new(user_params)
    if @user.save
      puts @user.provider
      if @user.provider == 'facebook'
        sign_in_and_redirect @user, success: 'Successfully signed up through Facebook'
      else
        redirect_to root_path, success: 'Successfully signed up'
      end
    else
      redirect_to root_path, danger: 'Log in through Facebook was not successful'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?

    if @user.update(user_params)
      flash[:info] = "Successfully updated User."
      redirect_to root_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = "Successfully deleted User."
      redirect_to root_path
    end
  end

  def download_file
    user = User.find_by(id: params[:id])
    if user.avatar.exists?
      send_file user.avatar.path
    else
      redirect_to user_path(user), warning: "No Image Found";
    end
  end


  def user_params
    params.require(:user).permit(:uid, :provider, :email, :last_name, :first_name, :markdown, :outstanding, :main_image, :avatar,:phone, :address, :country, :city, :avatar_file_name, :avatar_content_type, :avatar_file_size, :admin, :password, :password_confirmation)
  end


end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>


  <div class="col-sm-1">

  </div>

  <div class="col-sm-5">
    <div class="form-group">
      <%= form.label :first_name %><br/>
      <%= form.text_field :first_name, autocomplete: "first_name", class: "form-control", readonly: true %>
    </div>

    <div class="form-group">
      <%= form.label :last_name %><br/>
      <%= form.text_field :last_name, autocomplete: "last_name", class: "form-control", readonly: true %>
    </div>

    <div class="form-group">
      <%= form.label :email %><br/>
      <%= form.email_field :email, autocomplete: "email", class: "form-control", readonly: true %>
    </div>

    <div>
      <%= form.label :avatar %>
      <div class="input-group">
            <span class="input-group-btn">
                <span class="btn btn-default btn-file">
                  Browser...<%= form.file_field :avatar, class: "file", type: 'file'%>
                </span>
            </span>
        <input type="text" class="form-control" readonly>
      </div>
      <img id='img-upload'/>
    </div>

    <div class="form-group">
      <%= form.label :phone %><br/>
      <%= form.text_field :phone, autocomplete: "phone", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :address %><br/>
      <%= form.text_field :address, autocomplete: "address", class: "form-control" %>
    </div>

    <div>
      <%= form.label :country %><br/>
      <%= form.country_select :country, {prompt: 'Please select a country', selected: "CL", format: :with_alpha2}, class: 'form-control' %><br>
    </div>

    <div class="form-group">
      <%= form.label :city %><br/>
      <%= form.text_field :city, autocomplete: "city", class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Update", class: "btn btn-primary" %>
    </div>

  </div>

  <div class="col-sm-5">
    <%= image_tag("facebook_logo.png", alt: "Edit Entry", class: "img-responsive") %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h1>Editing Facebook Profile</h1>
  <%= render 'form', user: @users %>
</div>

app/views/users/new_facebook.html.erb
<div class="container">
  <div class="form col-sm-5">
    <h2>Sign up with Facebook</h2>
    <%= form_for(@user, url: users_path(@user), :html => { :multipart => true }) do |f| %>

      <%= f.hidden_field :first_name, autofocus: true, autocomplete: @user.first_name, class: "form-control" %>
      <%= f.hidden_field :last_name, autocomplete: @user.last_name, class: "form-control" %>
      <%= f.hidden_field :uid, autocomplete: @user.uid, class: "form-control" %>
      <%= f.hidden_field :provider, autocomplete: @user.provider, class: "form-control" %>

      <div class="form-group">
        <%= f.label :avatar %>
        <div class="input-group">
            <span class="input-group-btn">
                <span class="btn btn-default btn-file">
                  Browser...<%= f.file_field :avatar, class: "file", type: 'file'%>
                </span>
            </span>
          <input type="text" class="form-control" readonly>
        </div>
        <img id='img-upload'/>
      </div>

      <div class="form-group">
        <%= f.hidden_field :email, autocomplete: @user.email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :phone %><br/>
        <%= f.text_field :phone, autocomplete: "phone", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :address %><br/>
        <%= f.text_field :address, autocomplete: "address", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :country %><br/>
        <%= f.country_select :country, {prompt: 'Please select a country', selected: "CL", format: :with_alpha2}, class: 'form-control' %><br>
      </div>

      <div class="form-group">
        <%= f.label :city %><br/>
        <%= f.text_field :city, autocomplete: "city", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.hidden_field :password, value: @user.password, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.hidden_field :password_confirmation, value: @user.password, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit "Sign up", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <div class="col-sm-7" align="center" style="padding-top: 100px">
    <%= image_tag("crowdfunding_world.png", alt: "Edit Entry", class: "img-responsive") %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="img-wrapper" align="center">
    <% if @user.avatar.exists? %>
      <%= image_tag(@user.avatar.url(:medium),size: "200x200", class: "thumb1 img-circle") %>
    <% else %>
      <%= image_tag("generic_profile.jpeg",size: "200x200", class: "thumb1 img-circle") %>
    <% end %>
    <% if user_signed_in? %>
      <% if @user.id == current_user.id %>
        <div class="img-overlay2" align="left">

        </div>

        <div class="img-overlay">
          <% if @user.provider == 'facebook' %>
            <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-warning btn-sm" %>
          <% else %>
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "btn btn-warning btn-sm" %>
          <% end %>
          <%= link_to '<i class="fas fa-download"></i>'.html_safe, download_image_u_path(id: @user), class: "btn btn-default btn-sm" %>
        </div>
      <% end %>
    <% end %>

  </div>


  <div align="center" style="padding-top: 10px">
    <h1 style="font-size: 48px;"><%= @user.first_name %> <%= @user.last_name %></h1>
  </div>

  <div class="row" style="padding-top: 20px">
    <div class="col-sm-7 animated bounceInLeft">
      <div class="panel panel-success">
        <div class="panel-heading">Activities</div>
        <div class="panel-body">
          <h5><%= @user.first_name %> has: </h5>
          <ul>
            <li>Started <%= @projects %> campaigns.</li>
            <li>Founded exactly <%= @founded %> projects.</li>
            <li><%= @waiting %> contributions still waiting for approval.</li>
          </ul>
          <br>

        </div>
      </div>
      <%= link_to 'Projects', show_user_projects_path(id: @user.id), class: "btn btn-default btn-block" %>
    </div>

    <div class="col-sm-5 animated bounceInRight">
      <div class="panel panel-primary">
        <div class="panel-heading">Contact Information</div>
        <div class="panel-body">
          <strong><i class="far fa-envelope"></i> </strong><%= @user.email %><br>
          <strong><i class="fas fa-mobile-alt"></i> </strong><%= @user.phone %><br>
          <strong><i class="fas fa-home"></i> </strong><%= @user.address %>, <%= @user.city %>, <%= @user.country %><br>
          <%= link_to 'Download Profile Picture', download_image_u_path(id: @user), class: "btn btn-link btn-sm" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show_all.html.erb
<div class="container">
  <h1>All Users</h1>
  <p>Total: <%= User.all.count %> users</p>
  <table class="table">
    <thead>
    <tr>
      <th></th>
      <th>ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% User.all.each do |user| %>
      <td>
        <% if user.avatar.exists? %>
          <td><%= image_tag(user.avatar.url(:thumb), size: "25x25") %></td>
        <% else %>
          <td>-----</td>
        <% end %>
        <td><%= user.id %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>

        <td><div class="btn-group">
          <%= link_to 'Show', user, class: "btn btn-default", type: 'button' %>
          <%= link_to 'Edit', edit_user_path(user), class: "btn btn-default", type: 'button' %>
          <%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-default", type: 'button' %>
        </div></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>