config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories
  resources :favorites
  resources :projects
  resources :promises
  devise_for :users, :path_prefix => 'd', controllers: { :omniauth_callbacks => 'callbacks' }
  resources :finances do
    member do
      get :confirm_finance
    end
  end
  resources :users, only: [:show]
  get 'new_promise', to: 'promises#new'
  get 'my_projects', to: 'projects#show_my'
  get 'show_all', to: 'users#show_all'
  get 'show_my_fav', to: 'favorites#show_my_fav'
  get 'show_my_waiting', to: 'projects#show_my_waiting'
  get 'show_my_funded', to: 'projects#show_my_funded'
  get 'show_outstanding', to: 'projects#show_outstanding'
  get 'make_outstanding', to: 'projects#make_outstanding'
  get 'download_image_p', to: 'projects#download_file'
  get 'download_image_u', to: 'users#download_file'
  get 'contribution/create', to: 'contributions#create'
  get 'finance/create', to: 'finances#create'
  get 'new_facebook', to: 'users#new_facebook'
  resources :contributions do
    member do
      get :confirm_contribution
    end
  end

  resources :projects do
    put :favorite, on: :member
  end
  get 'show_by_cat', to: 'categories#show_by_cat'
  get 'show_user_projects', to: 'projects#show_user_projects'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
  resources :users, :controller => "users"
  resources :promises, :controller => "promises"

end

app/models/project.rb
class Project < ApplicationRecord
  has_attached_file :main_image, styles: { large: "900x900>", medium: "300x300>", small: "80x80#", thumb: "30x30#" }, default_url: "no_photo.png"
  validates_attachment_content_type :main_image, content_type: /\Aimage\/.*\z/
  belongs_to :user
  has_many :favorites, :dependent => :destroy
  has_many :contributions, :dependent => :destroy
  has_many :users, through: :contributions
  has_many :promises, :dependent => :destroy
  has_many :users, through: :favorites
  has_many :project_categories, :dependent => :destroy
  has_many :categories, through: :project_categories
  has_many :favorited_by, through: :favorites, source: :user

  validates :title, presence: true
  validates :description, presence: true
  validates :goal, presence: true
  validates :duration, presence: true
  validates :goal, numericality: { greater_than: 0 }

  def self.search(search)
    where("title LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%")
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show, :edit, :update, :destroy, :favorite, :download_file]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    if params[:filtered]
      @custom_search = true
    end
    if params[:search]
      @projects = Project.search(params[:search]).order("created_at DESC")
    else
      @projects = Project.all.order("created_at DESC")
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  def show_my
    @projects = current_user.projects
  end

  def show_user_projects
    id = params[:id]
    @projects = Project.all
    @user = User.find_by_id(id)
  end

  # GET /projects/new
  def new
    @project = Project.new

  end
  def show_my_waiting
    @my_projects = Project.where(user_id: current_user.id)
    @contributions = Contribution.where(project_id: @my_projects, status: false)
    @promises = Promise.where(project_id: @my_projects)
    @finances = Finance.joins(:promise).where(promise_id: @promises, status: false)
  end
  def show_my_funded
    @my_projects = Project.where(user_id: current_user.id)
    @contributions = Contribution.where(project_id: @my_projects, status: true)
    @promises = Promise.where(project_id: @my_projects)
    @finances = Finance.joins(:promise).where(promise_id: @promises, status: true)
  end
  def show_outstanding
    @projects = Project.where(outstanding: true)
  end
  # GET /projects/1/edit
  def edit
  end


  # POST /projects
  # POST /projects.json
  def create

    @project = Project.new(project_params)
    @project.user_id = current_user.id

    respond_to do |format|
      if @project.save

        format.html { redirect_to @project, success: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, info: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    if @project.user_id != current_user.id and current_user.admin == false
      return redirect_to root_path, danger: "Only admin user can delete this project"
    end
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, success: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def favorite
    type = params[:type]
    if type == "favorite"
      current_user.favorite_projects << @project
      redirect_back fallback_location: { action: "show", id: @project.id }, info: "Added to Wishlist"
    elsif type == "unfavorite"
      current_user.favorite_projects.delete(@project)
      redirect_back fallback_location: { action: "show", id: @project.id }, info: "Removed from Wishlist"
    else
      redirect_back fallback_location: { action: "show", id: @project.id }, info: "Nothing happend"
    end
  end

  def make_outstanding
    @project = Project.find(params[:format])
    if !(@project.main_image.exists?)
      @project.update(outstanding: false)
      redirect_back fallback_location: { action: "show", id: params[:id] }, warning: "Featured projects MUST have an image."
    elsif !(@project.outstanding)
      @project.update(outstanding: true)
      redirect_back fallback_location: { action: "show", id: params[:id] }, success: "This project is now outstanding"
    else
      @project.update(outstanding: false)
      redirect_back fallback_location: { action: "show", id: params[:id] }, success: "This project is no longer outstanding"
    end
  end
  def download_file
    if @project.main_image.exists?
      send_file @project.main_image.path
    else
        redirect_to project_path(@project), warning: "No Image Found";
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :goal, :duration, :markdown, :outstanding, :main_image, category_ids: [])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true, :html => { :multipart => true }) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
  <div class="form-group col-sm-5">
    <form>
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, id: :project_title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, id: :project_description, class: "form-control", rows: "4" %>
      </div>

      <div class="form-group">
        <%= form.label :goal %>
        <%= form.number_field :goal, id: :project_goal, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :duration %>
        <%= form.number_field :duration, id: :project_duration, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :markdown %>
        <%= form.text_area :markdown, id: :project_markdown, class: "form-control", rows: 15 %>
      </div>

      <div class="form-group">
        <%= form.label :main_image %>
        <div class="input-group">
            <span class="input-group-btn">
                <span class="btn btn-default btn-file">
                  Browser...<%= form.file_field :main_image, class: "file", type: 'file'%>
                </span>
            </span>
          <input type="text" class="form-control" readonly>
        </div>
        <img id='img-upload'/>
      </div>

      <div class="form-group">
        <label>Categories</label><br>
        <%= form.collection_check_boxes :category_ids, Category.all, :id, :tag do |option| %>
          <%= option.check_box + option.text %><br>
        <% end %>

      </div>

      <div class="actions">
        <button type="submit" class="btn btn-primary">Submit</button>
        <%= link_to 'Cancel', :back, class: "btn btn-danger" %>
      </div>
    </form>
  </div>

  <div class="col-sm-7" align="center" style="padding-top: 100px">
    <%= image_tag("crowdfunding_bubbles.png", alt: "Edit Entry", class: "img-responsive animated fadeInUp") %>
  </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="container">
  <h1>Editing Project</h1>

  <%= render 'form', project: @project %>

  <%= link_to 'Add Promises', new_promise_path(:project => @project.id), class: "btn btn-info btn-sm btn-block" %>

</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="row">
    <% if @custom_search %>
      <h1>Results for <b>"<%= params[:search] %>"</b></h1>
    <% else %>
      <h1>All Projects</h1>
    <% end %>
    <% if @projects.blank? && @custom_search%>
      <p>There are no projects containing the term <%= params[:search] %>.</p>
    <% end %>
    <%= link_to "Filter", categories_path, class: "btn btn-link"%>
    <br>
    <br>
      <% @projects.each do |project| %>
        <div class="row animated fadeIn">
          <div class="col-sm-5">
            <%= link_to(image_tag(project.main_image.url(:large), class: "img-fluid img-thumbnail"), project, class: "img-fluid") %>
            <%= %>
          </div>
          <div class="col-sm-5" style="padding-top: 35px">
            <div class="row">
              <h3><%= project.title %></h3>
              <p><%= project.description %></p>
              <br>
              <div class="col-sm-6" align="center">
                <p><b>Goal: </b>$<%= project.goal %></p>
              </div>
              <div class="col-sm-6" align="center">
                <p>Ends <%= (project.created_at.to_date + (project.duration).months).strftime("%B %e, %Y") %></p>
              </div>
            </div>
            <div class="row" align="center">
              <% if user_signed_in? %>
                <% if current_user.admin %>
                  <br>
                  <%= link_to 'Mark as Outstanding', make_outstanding_path(project), :class => "btn btn-default btn-sm" %>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="col-sm-2" style="padding-top: 70px">
            <div class="btn-group-vertical" style="width: 100%;">
              <%= link_to 'Show', project, class: "btn btn-default btn-block", type: 'button' %>
              <% if user_signed_in? %>
                <% if current_user.id == project.user_id or current_user.admin %>
                  <%= link_to 'Edit', edit_project_path(project), class: "btn btn-default btn-block", type: 'button' %>
                  <%= link_to 'Delete', project, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-default btn-block", type: 'button' %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <br>
      <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <h1>New Project</h1>

  <%= render 'form', project: @project %>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="row" style="padding-top: 50px">
    <div class="col-sm-6" style="padding-top: 75px" id = "divprincipal">
      <!-- SHOW SLIDESHOW WITH IMAGE AND VIDEO -->
      <%= link_to (image_tag(@project.main_image.url(:large), class: "img-fluid img-thumbnail")), download_image_p_path(id: @project) %>
      <br>
      <br>
      <div class="col-sm-6">
        <%= link_to 'Get to know the publisher', @project.user, :class => "btn btn-info btn-sm" %>

      </div>



      <div class="col-sm-6" align="right">
        <% if user_signed_in? %>
          <% if !(current_user.favorite_projects.include?(@project)) %>
            <%= link_to "Add to Wishlist", favorite_project_path(@project, type: "favorite"), method: :put, class: "btn btn-success btn-sm" %>
          <% else %>
            <%= link_to "Remove from Wishlist", favorite_project_path(@project, type: "unfavorite"), method: :put, class: "btn btn-danger btn-sm" %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-sm-6" style="padding-left: 100px; padding-right: 75px">
      <div class="row" align="center">
        <h1><%= @project.title %></h1>
        <% if user_signed_in? %>
          <% if current_user.id == @project.user_id %>
            <%= link_to 'Edit Project', edit_project_path(@project), :class => "btn btn-warning btn-sm" %>
          <% end %>
          <% if current_user.admin %>
            <%= link_to 'Mark as Outstanding', make_outstanding_path(@project), :class => "btn btn-default btn-sm" %>
          <% end %>
        <% end %>
      </div>
      <div class="row">
        <h4>Categories</h4>
        <% @project.categories.each do |category| %>
          <b style="font-size: 15px; font-style: italic; color: #666666">* <%= category.tag %></b>
        <% end %>
        <br><br>
        <h4>Description</h4>
        <p><%= @project.description %></p>
      </div>
      <br>
      <div class="row" align="center">
        <%
          sum = 0
          @project.contributions.each do |item|
            if item.status == true
              sum += item.amount
             end
          end
          Finance.all.each do |item|
            if item.promise.project.id == @project.id
              if item.status == true
                 sum += item.promise.amount
              end
            end
          end
          porcentage = 100*sum/@project.goal
          if porcentage > 100
            porcentage = 100
          end
        %>
        <p align="right"><strong>Goal: </strong>$<%= @project.goal %></p>
        <div class="progress">
          <div class="progress-bar" role="progressbar" style="width: <%= porcentage %>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">$ <%= sum %></div>
        </div>
        <% if porcentage == 100 %>
          <div class="animated tada">
            <b style="font-size: 48px"><i>Thank you!</i></b>
          </div>
          <p class="blockquote-footer">We have reached our goal because of all of you and we thank you for believing in our project.</p><br><br>

        <% end %>
        <b style="font-size: 24px; color: coral;">$<%= sum %> Collected</b>
        <p style="font-size: 20px; color: goldenrod;">Campaign open until <%= (@project.created_at.to_date + (@project.duration).months).strftime("%B %e, %Y") %></p>
        <br>
      </div>
      <% if user_signed_in? %>
        <div class="row">
          <h4>Promises</h4>
          <% if @project.promises.count == 0%>

            <p>This project doesn't have any promises.</p>
          <% end %>
          <div>
            <table class="table">
              <tbody>
                <% @project.promises.each do |promise|%>
                  <tr>
                    <td><%= promise.title %></td>
                    <td>$<%= promise.amount %></td>
                    <td align="center">
                      <%= link_to 'Buy', new_finance_path(promise: promise, project: @project), class: 'btn btn-success btn-sm' %>
                      </button>
                      <% if current_user == @project.user %>
                        <div class="btn-group">
                          <%= link_to 'Edit', edit_promise_path(promise), class: 'btn btn-default btn-sm' %>
                          <%= link_to 'Delete', promise, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-default btn-sm", type: 'button' %>
                        </div>
                      <% end %>
                    </td>
                  </tr>
                <%end%>
              </tbody>
            </table>

          </div>
        </div>
        <!-- Modal -->
        <div class="modal fade" align="center" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-body">
                An E-mail was send to <b><%= current_user.email %></b> in order to follow up on transaction.
              </div>
            </div>
          </div>
        </div>
        <br>
        <div class="row" id = 'botnfunding' align="center">
          <button id = "btn1" class="btn btn-warning btn-lg btn-block" ><b>Support this Project</b></button>
        </div>
      <% end %>
    </div>
  </div>
  <br>
  <% if @project.markdown != '' %>
    <div style="outline: 1px solid darkgray; padding: 25px; background: rgba(255,255,255,0.3);">
      <%= markdown(@project.markdown) %>
    </div>
  <% end %>
</div>
<script> $('#btn1').click(function () {

    var pur= "<%= @project.id%>"
    var neww = " <form action=\"/contribution/create\">\n" +
        "  Amount:<br>\n" +
        "  <input class= \"form-control\" type=\"number\" name=\"amount\" ><br>\n" +
        "  <input type=\"hidden\" name=\"project_id\" value="+pur+" >\n" +

        "  <input class=\"btn btn-success btn-sm\" type=\"submit\" value=\"Submit\">\n" +
        "</form> "


    var newtext = " Amount:<br>\n" +"  <input type=\"number\" name=\"lastname\">"
    $('#botnfunding').append(neww);

    $('#btn1').remove();


})


</script>>

app/views/projects/show_my.html.erb
<div class="container">
  <div class="row">
    <div class="btn-group">
      <%= link_to 'All', my_projects_path, class: "btn btn-default btn-sm", type: "button" %>
      <%= link_to 'Waiting', show_my_waiting_path, class: "btn btn-default btn-sm", type: "button" %>
      <%= link_to 'Funded', show_my_funded_path, class: "btn btn-default btn-sm", type: "button" %>
    </div>
  </div>
  <h1>Projects</h1>
    <% current_user.projects.each do |project| %>
      <div class="row animated fadeIn">
        <div class="col-sm-5">
          <%= link_to(image_tag(project.main_image.url(:large), class: "img-fluid img-thumbnail"), project, class: "img-fluid") %>
          <%=  %>
        </div>
        <div class="col-sm-5" style="padding-top: 35px">
          <h3><%= project.title %></h3>
          <p><%= project.description %></p>
          <br>
          <div class="col-sm-6" align="center">
            <p><b>Goal: </b>$<%= project.goal %></p>
          </div>
          <div class="col-sm-6" align="center">
            <p>Ends <%= (project.created_at.to_date + (project.duration).months).strftime("%B %e, %Y") %></p>
          </div>
        </div>
        <div class="col-sm-2" style="padding-top: 70px">

          <div class="btn-group-vertical" style="width: 100%;">
            <%= link_to 'Show', project, class: "btn btn-default btn-block", type: 'button' %>
            <% if user_signed_in? %>
              <% if current_user.id == project.user_id or current_user.admin %>
                <%= link_to 'Edit', edit_project_path(project), class: "btn btn-default btn-block", type: 'button' %>
                <%= link_to 'Delete', project, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-default btn-block", type: 'button' %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <br>
    <% end %>
</div>

app/views/projects/show_my_funded.html.erb
<div class="container">
  <div class="row">
    <div class="btn-group">
      <%= link_to 'All', my_projects_path, class: "btn btn-default btn-sm", type: "button" %>
      <%= link_to 'Waiting', show_my_waiting_path, class: "btn btn-default btn-sm", type: "button" %>
      <%= link_to 'Funded', show_my_funded_path, class: "btn btn-default btn-sm", type: "button" %>
    </div>
  </div>
  <h1>Projects Funded  </h1>
  <table class="table">
    <thead>
    <tr>
      <th>Title</th>
      <th>Amount</th>
      <th>Type</th>
      <th>Promise Title</th>
      <th>User Who Donated</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>

    <% @contributions.each do |contribution| %>
      <tr>
        <td><%= contribution.project.title %></td>
        <td><%= contribution.amount %></td>
        <td>Contribution</td>
        <td>---</td>
        <td><%= contribution.user.first_name %></td>
        <td><%= link_to 'Show project', contribution.project, :class => "btn btn-link" %></td>
      </tr>
    <%end%>
    <% @finances.each do |finance| %>
      <tr>
        <td><%= finance.promise.project.title %></td>
        <td><%= finance.promise.amount%></td>
        <td>Promise</td>
        <td><%= finance.promise.title%></td>
        <td><%= finance.user.first_name %></td>
        <td><%= link_to 'Show project', finance.promise.project, :class => "btn btn-link" %></td>
      </tr>
    <% end %>



    </tbody>
  </table>
</div>

app/views/projects/show_my_waiting.html.erb
<div class="container">


  <div class="row">
    <div class="btn-group">
      <%= link_to 'All', my_projects_path, class: "btn btn-default btn-sm", type: "button" %>
      <%= link_to 'Waiting', show_my_waiting_path, class: "btn btn-default btn-sm", type: "button" %>
      <%= link_to 'Funded', show_my_funded_path, class: "btn btn-default btn-sm", type: "button" %>
    </div>
  </div>
  <h1>Projects Waiting For Funding  </h1>
  <table class="table">
    <thead>
    <tr>
      <th>Title</th>
      <th>Amount</th>
      <th>Type</th>
      <th>Promise Title</th>
      <th>User Who Donated</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>

    <% @contributions.each do |contribution| %>
      <tr>
        <td><%= Project.find_by(id: contribution.project_id).title %></td>
        <td><%= contribution.amount %></td>
        <td>Contribution</td>
        <td>---</td>
        <td><%= User.find_by(id:contribution.user_id).first_name%></td>
        <td><%= link_to 'Show project', Project.find_by(id: contribution.project_id), :class => "btn btn-link" %></td>
      </tr>
    <%end%>
    <% @finances.each do |finance| %>
      <tr>
        <td><%= Project.find_by(id: Promise.find_by(id:finance.promise_id).project_id).title %></td>
        <td><%= Promise.find_by(id: finance.promise_id).amount%></td>
        <td>Promise</td>
        <td><%= Promise.find_by(id: finance.promise_id).title%></td>
        <td><%= User.find_by(id: finance.user_id).first_name %></td>
        <td><%= link_to 'Show project', Project.find_by(id: Promise.find_by(id: finance.promise_id).id), :class => "btn btn-link" %></td>
      </tr>
    <% end %>



    </tbody>
  </table>
</div>

app/views/projects/show_outstanding.html.erb
<div class="container">
  <h1>Outstanding Projects</h1>
    <% @projects.each do |project| %>
      <div class="row animated fadeIn">
        <div class="col-sm-5">
          <%= link_to(image_tag(project.main_image.url(:large), class: "img-fluid img-thumbnail"), project, class: "img-fluid") %>
          <%=  %>
        </div>
        <div class="col-sm-5" style="padding-top: 35px">
          <div class="row">
            <h3><%= project.title %></h3>
            <p><%= project.description %></p>
            <br>
            <div class="col-sm-6" align="center">
              <p><b>Goal: </b>$<%= project.goal %></p>
            </div>
            <div class="col-sm-6" align="center">
              <p>Ends <%= (project.created_at.to_date + (project.duration).months).strftime("%B %e, %Y") %></p>
            </div>
          </div>
          <div class="row" align="center">
            <% if user_signed_in? %>
              <% if current_user.admin %>
                <br>
                <%= link_to 'Mark as Outstanding', make_outstanding_path(@project), :class => "btn btn-default btn-sm" %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="col-sm-2" style="padding-top: 70px">

          <div class="btn-group-vertical" style="width: 100%;">
            <%= link_to 'Show', project, class: "btn btn-default btn-block", type: 'button' %>
            <% if user_signed_in? %>
              <% if current_user.id == project.user_id or current_user.admin %>
                <%= link_to 'Edit', edit_project_path(project), class: "btn btn-default btn-block", type: 'button' %>
                <%= link_to 'Delete', project, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-default btn-block", type: 'button' %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <br>
    <% end %>
</div>

app/views/projects/show_user_projects.html.erb
<div class="container">
  <h1>Projects by <%= @user.first_name %></h1>
  <br>
  <% @projects.each do |project| %>
    <% if project.user_id == @user.id %>
      <div class="row animated fadeIn">
        <div class="col-sm-5">
          <%= link_to(image_tag(project.main_image.url(:large), class: "img-fluid img-thumbnail"), project, class: "img-fluid") %>
          <%= %>
        </div>
        <div class="col-sm-5" style="padding-top: 35px">
          <div class="row">
            <h3><%= project.title %></h3>
            <p><%= project.description %></p>
            <br>
            <div class="col-sm-6" align="center">
              <p><b>Goal: </b>$<%= project.goal %></p>
            </div>
            <div class="col-sm-6" align="center">
              <p>Ends <%= (project.created_at.to_date + (project.duration).months).strftime("%B %e, %Y") %></p>
            </div>
          </div>
          <div class="row" align="center">
            <% if user_signed_in? %>
              <% if current_user.admin %>
                <br>
                <%= link_to 'Mark as Outstanding', make_outstanding_path(project), :class => "btn btn-default btn-sm" %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="col-sm-2" style="padding-top: 70px">
          <div class="btn-group-vertical" style="width: 100%;">
            <%= link_to 'Show', project, class: "btn btn-default btn-block", type: 'button' %>
            <% if user_signed_in? %>
              <% if current_user.id == project.user_id or current_user.admin %>
                <%= link_to 'Edit', edit_project_path(project), class: "btn btn-default btn-block", type: 'button' %>
                <%= link_to 'Delete', project, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-default btn-block", type: 'button' %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    <br>
  <% end %>
</div>