config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories
  resources :favorites
  resources :projects
  resources :promises
  devise_for :users, :path_prefix => 'd', controllers: { :omniauth_callbacks => 'callbacks' }
  resources :finances do
    member do
      get :confirm_finance
    end
  end
  resources :users, only: [:show]
  get 'new_promise', to: 'promises#new'
  get 'my_projects', to: 'projects#show_my'
  get 'show_all', to: 'users#show_all'
  get 'show_my_fav', to: 'favorites#show_my_fav'
  get 'show_my_waiting', to: 'projects#show_my_waiting'
  get 'show_my_funded', to: 'projects#show_my_funded'
  get 'show_outstanding', to: 'projects#show_outstanding'
  get 'make_outstanding', to: 'projects#make_outstanding'
  get 'download_image_p', to: 'projects#download_file'
  get 'download_image_u', to: 'users#download_file'
  get 'contribution/create', to: 'contributions#create'
  get 'finance/create', to: 'finances#create'
  get 'new_facebook', to: 'users#new_facebook'
  resources :contributions do
    member do
      get :confirm_contribution
    end
  end

  resources :projects do
    put :favorite, on: :member
  end
  get 'show_by_cat', to: 'categories#show_by_cat'
  get 'show_user_projects', to: 'projects#show_user_projects'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
  resources :users, :controller => "users"
  resources :promises, :controller => "promises"

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :project_categories
  has_many :projects, through: :project_categories

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy, :favorite]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.group(:tag)

  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end
  def show_by_cat
    @categories = Category.where(tag: params[:format])
    @tagname = params[:format]
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, success: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, info: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, success: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:tag, :project_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-sm-5">
    <div class="form-group">
      <%= form.label :tag %>
      <%= form.text_field :tag, id: :category_tag, class: "form-control" %>
    </div>

    <div class="actions" align="center">
      <%= form.submit "Create", class: "btn btn-primary btn-sm" %>
      <%= link_to 'Back', :back, class: "btn btn-danger btn-sm" %>
    </div>
  </div>

<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <h1>Editing Category</h1>

  <%= render 'form', category: @category %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <h1 class="animated slideInUp">Categories</h1>
  <br>
  <%= link_to "Featured Projects", show_outstanding_path, class: "btn btn-warning btn-lg btn-block animated bounceIn" %>
  <br><br>
  <%= link_to "All", projects_path, class: "btn btn-default btn-lg btn-block animated bounceIn" %>
  <% if user_signed_in? %>
    <% if current_user.admin %>
      <br>
      <% @categories.each do |category| %>
        <div class="col-sm-10">
          <%= link_to category.tag, show_by_cat_path(category.tag), class: "btn btn-default btn-lg btn-block animated bounceIn" %>
        </div>
        <div class="col-sm-2">
          <div class="btn-group btn-group-justified animated bounceIn">
            <%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_category_path(category), class: "btn btn-default btn-lg" %>
            <%= link_to '<i class="far fa-minus-square", size="6x"></i>'.html_safe, category, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-default btn-lg" %>
          </div>

        </div>
      <% end %>
    <% else %>
      <% @categories.each do |category| %>
        <%= link_to category.tag, show_by_cat_path(category.tag), class: "btn btn-default btn-lg btn-block animated bounceIn" %>
      <% end %>
    <% end %>
  <% else %>
    <% @categories.each do |category| %>
      <%= link_to category.tag, show_by_cat_path(category.tag), class: "btn btn-default btn-lg btn-block animated bounceIn" %>
    <% end %>
  <% end %>
  <br>
</div>

app/views/categories/new.html.erb
<div class="container">
  <h1>New Category</h1>
  <%= render 'form', category: @category %>
</div>

app/views/categories/show.html.erb
<div class="container" align="center">
  <h1 style="padding-top: 250px; font-size: 48px">
    Category <strong><%= @category.tag %></strong> created.
  </h1>
  <br>
  <%= link_to 'See All Catorigies', categories_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/categories/show_by_cat.html.erb
<div class="container">
  <h1><%=@tagname%> Projects</h1>
    <% @categories.each do |category| %>
        <%category.projects.each do |project|%>
          <div class="row animated fadeIn">
            <div class="col-sm-5">
              <%= link_to(image_tag(project.main_image.url(:large), class: "img-fluid img-thumbnail"), project, class: "img-fluid") %>
              <%= %>
            </div>
            <div class="col-sm-5" style="padding-top: 35px">
              <div class="row">
                <h3><%= project.title %></h3>
                <p><%= project.description %></p>
                <br>
                <div class="col-sm-6" align="center">
                  <p><b>Goal: </b>$<%= project.goal %></p>
                </div>
                <div class="col-sm-6" align="center">
                  <p>Ends <%= (project.created_at.to_date + (project.duration).months).strftime("%B %e, %Y") %></p>
                </div>
              </div>
              <div class="row" align="center">
                <% if user_signed_in? %>
                  <% if current_user.admin %>
                    <br>
                    <%= link_to 'Mark as Outstanding', make_outstanding_path(project), :class => "btn btn-default btn-sm" %>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="col-sm-2" style="padding-top: 70px">

              <div class="btn-group-vertical" style="width: 100%;">
                <%= link_to 'Show', project, class: "btn btn-default btn-block", type: 'button' %>
                <% if user_signed_in? %>
                  <% if current_user.id == project.user_id or current_user.admin %>
                    <%= link_to 'Edit', edit_project_path(project), class: "btn btn-default btn-block", type: 'button' %>
                    <%= link_to 'Delete', project, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-default btn-block", type: 'button' %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <br>
         <% end %>
    <% end %>
</div>