config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :categories
  resources :favorites
  resources :projects
  resources :promises
  devise_for :users, :path_prefix => 'd', controllers: { :omniauth_callbacks => 'callbacks' }
  resources :finances do
    member do
      get :confirm_finance
    end
  end
  resources :users, only: [:show]
  get 'new_promise', to: 'promises#new'
  get 'my_projects', to: 'projects#show_my'
  get 'show_all', to: 'users#show_all'
  get 'show_my_fav', to: 'favorites#show_my_fav'
  get 'show_my_waiting', to: 'projects#show_my_waiting'
  get 'show_my_funded', to: 'projects#show_my_funded'
  get 'show_outstanding', to: 'projects#show_outstanding'
  get 'make_outstanding', to: 'projects#make_outstanding'
  get 'download_image_p', to: 'projects#download_file'
  get 'download_image_u', to: 'users#download_file'
  get 'contribution/create', to: 'contributions#create'
  get 'finance/create', to: 'finances#create'
  get 'new_facebook', to: 'users#new_facebook'
  resources :contributions do
    member do
      get :confirm_contribution
    end
  end

  resources :projects do
    put :favorite, on: :member
  end
  get 'show_by_cat', to: 'categories#show_by_cat'
  get 'show_user_projects', to: 'projects#show_user_projects'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#index'
  resources :users, :controller => "users"
  resources :promises, :controller => "promises"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AZ Crowdfunding</title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'icon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
</head>

<body>

<script>
    window.fbAsyncInit = function() {
        FB.init({
            appId      : '{your-app-id}',
            cookie     : true,
            xfbml      : true,
            version    : '{latest-api-version}'
        });

        FB.AppEvents.logPageView();

    };

    (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "https://connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
  <div class="container">
    <div class="navbar-header" >
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar" style="background-color: black"></span>
        <span class="icon-bar" style="background-color: black"></span>
        <span class="icon-bar" style="background-color: black"></span>
      </button>
      <%= link_to root_path do %>
        <%= image_tag("logo2.png", alt: "Edit Entry", align: "middle", class: 'navbar-brand') %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><%= link_to "Categories", categories_path  %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= form_tag(projects_path, :method => "get", class: 'navbar-form navbar-right', id: "search-form") do %>
            <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Search" %>
            <%= hidden_field_tag :filtered, params[:filtered], value: true %>
            <%= submit_tag "Search", class: 'btn btn-default', :name => nil %>
          <% end %>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Projects</a>
              <div class="dropdown-menu">
                <a><%= link_to "My Projects", my_projects_path, class: "btn"  %></a>
                <br>
                <a><%= link_to "Wishlist", show_my_fav_path, class: "btn" %></a>
                <br>
                <div role="separator" class="divider"></div>
                <a><%= link_to "New Project", new_project_path, class: "btn" %></a>
              </div>
            </li>
            <li><%= link_to current_user.first_name, current_user %></li>
          <% if current_user.admin %>
            <li><%= link_to 'Admin', rails_admin_path, class: 'navbar_link' %></li>
          <% end %>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>

        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %></li>
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% if flash %>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  <% end %>
</div>
<%= yield %>
</body>
</html>